### ISSUE TITLE
[Error] python run.py 실행 시 생기는 문제

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#5]
[에러 메세지]

![import inplace_abn issue screenshot](https://user-images.githubusercontent.com/107831875/229953809-1b291ae4-adbc-40a4-8ca7-39bfa6b77b7b.png)

[터미널 창 전체 내용]

PS D:\acgpn-colab-original> python run.py
?
D:\acgpn-colab-original
D:\acgpn-colab-original\U-2-Net
...load U2NEP---4.7 MB
?
D:\acgpn-colab-original\U-2-Net
D:\acgpn-colab-original\U-2-Net\U-2-Net
...load U2NEP---4.7 MB
Generating mask for: img_1680619645.png
Saving output at D:/acgpn-colab-original/Data_preprocessing/test_edge\img_1680619645.png
Generating mask for: img_1680653555.png
Saving output at D:/acgpn-colab-original/Data_preprocessing/test_edge\img_1680653555.png
Generating mask for: img_1680655505.png
Saving output at D:/acgpn-colab-original/Data_preprocessing/test_edge\img_1680655505.png
옷 마스크 추출
img_1680655505.png
D:/acgpn-colab-original/inputs/cloth\000048_1.jpg
모델 마스크 추출
img_1680655521.png
D:/acgpn-colab-original/Data_preprocessing/test_img\img_1680655521.png
여기임
D:\acgpn-colab-original\U-2-Net
여기임
바꾼 디렉
D:\acgpn-colab-original
바꾼 디렉
simpleextracter.py 왔다감
Traceback (most recent call last):
  File "D:\acgpn-colab-original\Self-Correction-Human-Parsing-for-ACGPN\simple_extractor.py", line 26, in <module>
    import networks
  File "D:\acgpn-colab-original\Self-Correction-Human-Parsing-for-ACGPN\networks\__init__.py", line 3, in <module>
    from networks.AugmentCE2P import resnet101
  File "D:\acgpn-colab-original\Self-Correction-Human-Parsing-for-ACGPN\networks\AugmentCE2P.py", line 21, in <module>
    from modules import InPlaceABNSync
  File "D:\acgpn-colab-original\Self-Correction-Human-Parsing-for-ACGPN\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\acgpn-colab-original\Self-Correction-Human-Parsing-for-ACGPN\modules\bn.py", line 10, in <module>
    from .functions import *
  File "D:\acgpn-colab-original\Self-Correction-Human-Parsing-for-ACGPN\modules\functions.py", line 10, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1929, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing inplace_abn: 지정된 모듈을 찾을 수 없습니다.
D:\acgpn-colab-original
[ WARN:0@36.601] global ocl4dnn_conv_spatial.cpp:1923 cv::dnn::ocl4dnn::OCL4DNNConvSpatial<float>::loadTunedConfig OpenCV(ocl4dnn): consider to specify kernel configuration cache directory through OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!
File saved at D:/acgpn-colab-original/Data_preprocessing/test_pose\img_1680655521_keypoints.json
D:\acgpn-colab-original
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
continue_train: False
data_type: 32
datapairs: test_pairs.txt
dataroot: Data_preprocessing/
display_winsize: 512
engine: None
export_onnx: None
fineSize: 512
gpu_ids: [0]
how_many: 1000
input_nc: 3
isTrain: False
label_nc: 20
loadSize: 512
max_dataset_size: inf
model: pix2pixHD
nThreads: 1
n_blocks_global: 4
n_blocks_local: 3
n_downsample_global: 4
n_local_enhancers: 1
name: label2city
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
norm: instance
ntest: inf
onnx: None
output_nc: 3
phase: test
resize_or_crop: scale_width
results_dir: ./results/
serial_batches: True
tf_log: False
use_dropout: False
use_encoded_image: False
verbose: False
which_epoch: latest
-------------- End ----------------
opt =  Namespace(name='label2city', gpu_ids=[0], checkpoints_dir='./checkpoints', model='pix2pixHD', norm='instance', use_dropout=False, data_type=32, verbose=False, batchSize=1, loadSize=512, fineSize=512, label_nc=20, input_nc=3, output_nc=3, dataroot='Data_preprocessing/', datapairs='test_pairs.txt', resize_or_crop='scale_width', no_flip=False, nThreads=1, max_dataset_size=inf, display_winsize=512, tf_log=False, netG='global', ngf=64, n_downsample_global=4, n_blocks_global=4, n_blocks_local=3, n_local_enhancers=1, niter_fix_global=0, continue_train=False, ntest=inf, results_dir='./results/', aspect_ratio=1.0, phase='test', which_epoch='latest', how_many=1000, serial_batches=True, cluster_path='features_clustered_010.npy', use_encoded_image=False, export_onnx=None, engine=None, onnx=None, isTrain=False)
<class 'argparse.Namespace'>
여기는 dataloader
CustomDatasetDataLoader
dataset [AlignedDataset] was created
Data_preprocessing/test_label label
Data_preprocessing/test_img img
Data_preprocessing/test_edge edge
Data_preprocessing/test_edge edge
Data_preprocessing/test_mask mask
Data_preprocessing/test_mask mask
Data_preprocessing/test_colormask colormask
Data_preprocessing/test_colormask colormask
Data_preprocessing/test_color color
Data_preprocessing/test_color color
# Inference images = 0
모델 생성
latest_net_U.pth
latest_net_G1.pth
latest_net_G2.pth
latest_net_G.pth
여기는 지나감
dataset =  <torch.utils.data.dataloader.DataLoader object at 0x000001A51F44C460>
<class 'torch.utils.data.dataloader.DataLoader'>
0 1
?
D:\acgpn-colab-original
D:\acgpn-colab-original\U-2-Net
끝!

[dependency]

Package              Version
-------------------- ------------
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
certifi              2022.12.7
cffi                 1.15.0
charset-normalizer   3.1.0
colorama             0.4.5
cuda-python          12.1.0
cycler               0.11.0
Cython               0.29.34
debugpy              1.6.0
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
executing            0.8.3
fastjsonschema       2.15.3
filelock             3.10.7
fonttools            4.33.3
gdown                4.7.1
idna                 3.4
imageio              2.27.0
ipykernel            6.15.0
ipython              8.4.0
ipython-genutils     0.2.0
ipywidgets           7.7.1
jedi                 0.18.1
Jinja2               3.1.2
jsonpickle           3.0.1
jsonschema           4.6.0
jupyter              1.0.0
jupyter-client       7.3.4
jupyter-console      6.4.4
jupyter-core         4.10.0
jupyterlab-pygments  0.2.2
jupyterlab-widgets   1.1.1
kiwisolver           1.4.3
lazy_loader          0.2
MarkupSafe           2.1.1
matplotlib           3.5.2
matplotlib-inline    0.1.3
mistune              0.8.4
mpmath               1.3.0
nbclient             0.6.4
nbconvert            6.5.0
nbformat             5.4.0
nest-asyncio         1.5.5
networks             0.3.7
networkx             3.0
ninja                1.11.1
notebook             6.4.12
numpy                1.23.0
opencv-python        4.7.0.72
packaging            21.3
pandocfilters        1.5.0
parso                0.8.3
pickleshare          0.7.5
Pillow               9.1.1
pip                  23.0.1
prometheus-client    0.14.1
prompt-toolkit       3.0.30
protobuf             3.20.3
psutil               5.9.1
pure-eval            0.2.2
pycparser            2.21
Pygments             2.12.0
pyparsing            3.0.9
pyrsistent           0.18.1
PySocks              1.7.1
python-dateutil      2.8.2
PyWavelets           1.4.1
pywin32              304
pywinpty             2.0.5
pyzmq                23.2.0
qtconsole            5.3.1
QtPy                 2.1.0
requests             2.28.2
scikit-image         0.20.0
scipy                1.10.1
Send2Trash           1.8.0
setuptools           67.6.1
six                  1.16.0
soupsieve            2.3.2.post1
stack-data           0.3.0
sympy                1.11.1
tensorboardX         2.6
terminado            0.15.0
tifffile             2023.3.21
tinycss2             1.1.1
torch                2.0.0+cu118
torchaudio           2.0.1+cu118
torchvision          0.15.1+cu118
tornado              6.1
tqdm                 4.65.0
traitlets            5.3.0
typing_extensions    4.5.0
urllib3              1.26.15
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.40.0
widgetsnbextension   3.6.1

**Comment by troymerai** [comment]
#6 해결하고 다시 돌려보기

**Comment by troymerai** [comment]
리눅스 환경에서 다시 돌려볼 때까지 닫아두겠습니다.
