### ISSUE TITLE
[Error] pip install inplace-abn 실행 시 생기는 문제

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#6]
[에러 메세지]

![install inplace_abn issue screenshot](https://user-images.githubusercontent.com/107831875/229988037-d9362393-604c-4b5f-8d6f-909acad7cd64.png)

[터미널 창 내용]

PS D:\acgpn-colab-original> pip install inplace-abn
Collecting inplace-abn
  Using cached inplace-abn-1.1.0.tar.gz (137 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: inplace-abn
  Building wheel for inplace-abn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\abn.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\functions.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\group.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\_version.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\__init__.py -> build\lib.win-amd64-cpython-310\inplace_abn
      running build_ext
      error: [WinError 2] 지정된 파일을 찾을 수 없습니다
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
Installing collected packages: inplace-abn
  Running setup.py install for inplace-abn ... error
  error: subprocess-exited-with-error

  × Running setup.py install for inplace-abn did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running install      C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\abn.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\functions.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\group.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\_version.py -> build\lib.win-amd64-cpython-310\inplace_abn
      copying inplace_abn\__init__.py -> build\lib.win-amd64-cpython-310\inplace_abn
      running build_ext
      error: [WinError 2] 지정된 파일을 찾을 수 없습니다
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> inplace-abn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by troymerai** [comment]
Solution 1으로 pip install --use-pep517 inplace-abn 

[에러 메세지]

![install inplace_abn issue2 screenchot](https://user-images.githubusercontent.com/107831875/229988326-efbb4938-90dd-420b-a474-a71e1a5fcb14.png)

[터미널 창 전체 내용]

PS D:\acgpn-colab-original> pip install --use-pep517 inplace-abn
Collecting inplace-abn
  Using cached inplace-abn-1.1.0.tar.gz (137 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\mingk\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\mingk\AppData\Local\Temp\pip-build-env-26j80rvr\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\mingk\AppData\Local\Temp\pip-build-env-26j80rvr\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\mingk\AppData\Local\Temp\pip-build-env-26j80rvr\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\mingk\AppData\Local\Temp\pip-build-env-26j80rvr\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS D:\acgpn-colab-original>

**Comment by troymerai** [comment]
[시도해볼 것 정리]

- [x] 파이썬 재설치
- [ ] 파이썬 다운그레이드
- [x] 쿠다 재설치
- [ ] 쿠다 다운그레이드
- [x] 파이썬 dependency 재설치
- [x] 가상환경 새로 파서 install
- [x] inplace-abn github찾아보기
- [x] vscode 2019 재설치

**Comment by troymerai** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/107831875/232932772-4f41c49f-e3b2-4f7d-bd4d-6478bb6a60cf.png">
inplace-abn 리드미에서 발견한 내용입니다.
해당 패키지는 쿠다10.0+버전과 리눅스 환경에서만 돌아가기때문에 쿠다 12.0버전과 윈도우를 사용하는 제 머신에는 깔리지 않은 것 같습니다.

** 참고로 쿠다가 설치돼있지않은 윈도우 환경과 쿠다가 설치되어있지 않은 macos 환경에서는 해당 패키지가 설치되었지만, cuda가 없으면 다른 버전?의 inplace-abn 패키지가 받아지는 것 같습니다.

[해결방안]
일단 코랩환경에서 모델과 api를 완성하고, 시간이 남는다면 윈도우에서 가상 머신을 쓰거나 교수님께 실습서버 사용해도될지 여쭤보기

```
inplace-abn 패키지 깃허브 주소
https://github.com/mapillary/inplace_abn
```
